/**
 * Copyright (C) 2008 - Abiquo Holdings S.L. All rights reserved.
 *
 * Please see /opt/abiquo/tomcat/webapps/legal/ on Abiquo server
 * or contact contact@abiquo.com for licensing information.
 */
package com.abiquo.bond.plugins;

import com.abiquo.bond.api.annotations.HandleAnyEvent;
import com.abiquo.bond.api.event.APIEvent;
import com.abiquo.bond.api.plugin.AbstractPlugin;
import com.abiquo.bond.api.plugin.PluginException;

/**
 * A simple plugin example that receives all events generated by the Outbound API and just outputs
 * the specific class name of the APIEvent instance.
 */
public class AllEvents extends AbstractPlugin
{
    public AllEvents() throws Exception
    {
    }

    @HandleAnyEvent
    public void handleAnyEvent(final APIEvent event)
    {
        System.out.println("AllEvents: Received event of type " + event.getClass().getName());
    }

    @Override
    public String getName()
    {
        return "AllEvents sample plugin";
    }

    @Override
    public String getThreadName()
    {
        return "ABQ_PLUGIN_ALL_EVENTS";
    }

    @Override
    public void startup() throws PluginException
    {
        System.out.println("AllEvents:startup has been called");
    }

    /*
     * Simple example configuration that simple prints a message
     */
    public void configure()
    {
        System.out.println("AllEvents:configure has been called");
    }
}
