/**
 * Copyright (C) 2008 - Abiquo Holdings S.L. All rights reserved.
 *
 * Please see /opt/abiquo/tomcat/webapps/legal/ on Abiquo server
 * or contact contact@abiquo.com for licensing information.
 */
package com.abiquo.bond.plugins;

import java.util.concurrent.LinkedBlockingQueue;

import com.abiquo.bond.api.annotations.HandleBackupVMEvent;
import com.abiquo.bond.api.event.BackupVMEvent;
import com.abiquo.bond.api.plugin.AbstractPlugin;
import com.abiquo.bond.api.plugin.BackupPluginInterface;
import com.abiquo.bond.api.plugin.PluginException;
import com.abiquo.bond.api.response.BackupResultsHandler;
import com.abiquo.bond.api.response.VMBackupStatusList;

/**
 * A simple plugin example that receives only backup events generated by the Outbound API and just
 * outputs the specific class name of the BackupVMEvent instance.
 */
public class BackupEvents extends AbstractPlugin implements BackupPluginInterface
{
    public BackupEvents() throws Exception
    {
    }

    @HandleBackupVMEvent
    public void handleBackupEvent(final BackupVMEvent event)
    {
        System.out.println("BackupEvents: Received event of type " + event.getClass().getName());
    }

    @Override
    public String getName()
    {
        return "BackupEvents sample plugin";
    }

    @Override
    public String getThreadName()
    {
        return "ABQ_PLUGIN_BACKUP_EVENTS";
    }

    @Override
    public void startup() throws PluginException
    {
        System.out.println("BackupEvents:startup has been called");
    }

    /*
     * Simple example configuration that simple prints a message
     */
    public void configure()
    {
        System.out.println("BackupEvents:configure has been called");
    }

    @Override
    public BackupResultsHandler getResultsHandler() throws PluginException
    {
        return new SampleBackupResultsHandler();
    }
}

class SampleBackupResultsHandler implements BackupResultsHandler
{

    @Override
    public void run()
    {
        System.out.println("BackupEvents:SampleBackupResultsHandler:run has been called");
    }

    @Override
    public void setQueue(final LinkedBlockingQueue<VMBackupStatusList> queue)
    {
        System.out.println("BackupEvents:SampleBackupResultsHandler:setQueue has been called");
    }

}
